### ISSUE TITLE
Henry's priorities

### ISSUE THREAD

**Issue by henrypinkard** [micro-manager/LightSheetManager#4]
## Phase I: Immediately actionable improvements

- [x] (https://github.com/micro-manager/micro-manager/issues/1490)
- [ ] (https://github.com/micro-manager/micro-manager/issues/1465)
- [ ] (https://github.com/micro-manager/LightSheetManager/issues/8)

### New Camera API including triggering/GenICam/Light sheet
- [x] https://github.com/micro-manager/mmCoreAndDevices/issues/84
- [x] https://github.com/micro-manager/mmCoreAndDevices/issues/226
- [ ] (https://github.com/micro-manager/mmCoreAndDevices/issues/243)

### New image buffer/ memory mode
- [ ] https://github.com/micro-manager/mmCoreAndDevices/issues/244

### Acquisition engine abstractions for general purpose microscopes

- [ ] (https://github.com/micro-manager/micro-manager/issues/1524)

### C++ layer fast file saving
TDB
